
const NOTES_KEY='liv_ethic_notes_v11',LAYOUT_KEY='liv_ethic_layout_v11';
let notes=JSON.parse(localStorage.getItem(NOTES_KEY)||localStorage.getItem('liv_ethic_notes_v10')||localStorage.getItem('liv_ethic_notes_v9')||'[]');
let storedLayout={};try{storedLayout=JSON.parse(localStorage.getItem(LAYOUT_KEY)||'{}')||{};}catch(e){}
let categoryOrder=Array.isArray(storedLayout.categoryOrder)?storedLayout.categoryOrder:[];
if(!storedLayout.manualOrder)notes.sort((a,b)=>(Number(a.id)||0)-(Number(b.id)||0));
let currentViewMode='both',editingId=null,layoutFrame=0;
const noteForm=document.getElementById('noteForm'),noteList=document.getElementById('noteList'),filterThinker=document.getElementById('filterThinker'),filterStar=document.getElementById('filterStar'),pairContainer=document.getElementById('pairContainer'),originalInput=document.getElementById('originalText');
function escapeHtml(value){return String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function getCategory(n){return n.thinker||'공통/기타';}
function isConfusedNote(note){return note.recordType==='confused'||(note.recordType!=='correction'&&(!Array.isArray(note.corrections)||note.corrections.length===0));}
function updateRecordType(){const confused=document.getElementById('recordType').value==='confused';document.getElementById('correctionFields').hidden=confused;pairContainer.querySelectorAll('input,select,button').forEach(el=>{el.disabled=confused;});for(const row of pairContainer.children){row.querySelector('.wrong-input').required=!confused;row.querySelector('.target-select').required=!confused;const mark=row.querySelector('.action-select').value==='mark',correct=row.querySelector('.correct-input');correct.required=!confused&&!mark;correct.disabled=confused||mark;}document.getElementById('recordTypeHelp').textContent=confused?'틀린 부분이나 교정 위치를 입력하지 않아도 원문과 메모를 저장합니다. 메모는 비워도 됩니다.':'틀린 부분을 지정해서 교정하거나 × 표시를 남깁니다.';document.getElementById('submitNoteButton').textContent=editingId!==null?'수정 내용 저장':confused?'헷갈린 선지 기록하기':'오답 선지 추가하기';}
function syncCategoryOrder(){const names=[...new Set(notes.map(getCategory))];categoryOrder=[...new Set(categoryOrder)].filter(n=>names.includes(n));names.forEach(n=>{if(!categoryOrder.includes(n))categoryOrder.push(n);});}
function saveNotes(){syncCategoryOrder();FloveSync.saveBatch({[NOTES_KEY]:JSON.stringify(notes),[LAYOUT_KEY]:JSON.stringify({manualOrder:true,categoryOrder})});FloveSync.markSaved();}
function getNoteNumber(note){return notes.filter(n=>getCategory(n)===getCategory(note)).findIndex(n=>n===note||String(n.id)===String(note.id))+1;}
function nextId(){let id=Date.now();while(notes.some(n=>Number(n.id)===id))id++;return id;}
function occurrences(text,wrong){const positions=[];if(!wrong)return positions;let p=0;while((p=text.indexOf(wrong,p))!==-1){positions.push({start:p,end:p+wrong.length});p+=wrong.length;}return positions;}
function collectMatches(text,corrections){const all=[];(corrections||[]).forEach((c,order)=>{if(!c.wrong)return;const mark=c.action==='mark';if(Number.isInteger(c.start)&&Number.isInteger(c.end)){if(text.slice(c.start,c.end)===c.wrong)all.push({start:c.start,end:c.end,wrong:c.wrong,correct:c.correct||'',mark,order});}else occurrences(text,c.wrong).forEach(p=>all.push({...p,wrong:c.wrong,correct:c.correct||'',mark,order}));});all.sort((a,b)=>a.start-b.start||a.order-b.order);let end=0;return all.filter(m=>{if(m.start<end)return false;end=m.end;return true;});}
function updateTargetOptions(row,desired){const wrong=row.querySelector('.wrong-input').value,select=row.querySelector('.target-select'),keep=desired??select.value,positions=occurrences(originalInput.value,wrong);select.replaceChildren();const option=(label,value)=>{const o=document.createElement('option');o.textContent=label;o.value=value;select.appendChild(o);};option(wrong?(positions.length?'교정할 위치 선택':'원문에 일치하는 부분이 없음'):'틀린 부분을 입력하거나 원문에서 선택','');positions.forEach((p,i)=>{const before=originalInput.value.slice(Math.max(0,p.start-12),p.start),after=originalInput.value.slice(p.end,p.end+16);option(`${i+1}번째: ${before}[${wrong}]${after}`,`${p.start}:${p.end}`);});if(positions.length>1)option(`같은 부분 모두 (${positions.length}곳)`,'all');if([...select.options].some(o=>o.value===keep)&&keep)select.value=keep;else if(positions.length===1)select.value=`${positions[0].start}:${positions[0].end}`;select.required=true;updatePairPreview(row);}
function updatePairPreview(row){const text=originalInput.value,target=row.querySelector('.target-select').value,wrong=row.querySelector('.wrong-input').value,preview=row.querySelector('.target-preview');if(!target){preview.textContent='같은 글자가 여러 번 나오면 위치를 직접 골라 주세요.';return;}const matches=target==='all'?occurrences(text,wrong):[{start:Number(target.split(':')[0]),end:Number(target.split(':')[1])}];let html='',pos=0;matches.forEach(m=>{html+=escapeHtml(text.slice(pos,m.start))+`<mark>${escapeHtml(text.slice(m.start,m.end))}</mark>`;pos=m.end;});preview.innerHTML=html+escapeHtml(text.slice(pos));}
function updatePairMode(row){const mark=row.querySelector('.action-select').value==='mark',input=row.querySelector('.correct-input');input.required=!mark;input.disabled=mark;input.placeholder=mark?'교정 단어 없이 ×만 표시':'올바른 부분';input.style.opacity=mark?'.45':'1';}
function addPair(initial){initial=initial&&typeof initial==='object'?initial:{};const row=document.createElement('div');row.className='pair-row editor-pair';row.innerHTML=`<div class="pair-main"><input type="text" class="wrong-input" placeholder="틀린 부분" required><span class="sep-arrow">→</span><select class="action-select" aria-label="교정 방식"><option value="replace">단어 교정</option><option value="mark">× 표시만</option></select><input type="text" class="correct-input" placeholder="올바른 부분" required><button type="button" class="btn-remove-pair" title="교정 항목 삭제">✕</button></div><div class="pair-target"><button type="button" class="pick-selection">원문 선택 부분 지정</button><select class="target-select" aria-label="교정할 위치"></select></div><div class="target-preview"></div>`;row.querySelector('.wrong-input').value=initial.wrong||'';row.querySelector('.correct-input').value=initial.correct||'';row.querySelector('.action-select').value=initial.action==='mark'?'mark':'replace';row.querySelector('.wrong-input').addEventListener('input',()=>updateTargetOptions(row));row.querySelector('.action-select').addEventListener('change',()=>updatePairMode(row));row.querySelector('.target-select').addEventListener('change',()=>updatePairPreview(row));row.querySelector('.btn-remove-pair').addEventListener('click',()=>removePair(row));row.querySelector('.pick-selection').addEventListener('click',()=>{const start=originalInput.selectionStart,end=originalInput.selectionEnd;if(start===end){alert('먼저 원문에서 교정할 글자나 구절을 드래그해서 선택해 주세요.');originalInput.focus();return;}row.querySelector('.wrong-input').value=originalInput.value.slice(start,end);updateTargetOptions(row,`${start}:${end}`);});pairContainer.appendChild(row);updatePairMode(row);const desired=Number.isInteger(initial.start)&&Number.isInteger(initial.end)?`${initial.start}:${initial.end}`:initial.wrong?'all':'';updateTargetOptions(row,desired);updateRecordType();}
function removePair(row){if(pairContainer.children.length>1)row.remove();else alert('최소 하나의 교정 항목은 있어야 합니다.');}
function cancelEdit(){editingId=null;noteForm.reset();pairContainer.replaceChildren();addPair();document.getElementById('submitNoteButton').textContent='오답 선지 추가하기';document.getElementById('cancelEditButton').hidden=true;document.getElementById('editStatus').hidden=true;updateRecordType();}
function startEdit(note){editingId=note.id;document.getElementById('thinker').value=note.thinker||'';document.getElementById('reasonTag').value=note.reasonTag||'';document.getElementById('sourceInput').value=note.source||'';originalInput.value=note.originalText;document.getElementById('memo').value=note.memo||'';document.getElementById('recordType').value=isConfusedNote(note)?'confused':'correction';pairContainer.replaceChildren();(note.corrections?.length?note.corrections:[{}]).forEach(addPair);updateRecordType();document.getElementById('submitNoteButton').textContent='수정 내용 저장';document.getElementById('cancelEditButton').hidden=false;const status=document.getElementById('editStatus');status.hidden=false;status.textContent=`${getCategory(note)} · 기출 ${getNoteNumber(note)} 수정 중`;noteForm.scrollIntoView({behavior:'smooth',block:'start'});}
noteForm.addEventListener('submit',event=>{event.preventDefault();const text=originalInput.value,corrections=[],recordType=document.getElementById('recordType').value;if(!text.trim()||!document.getElementById('thinker').value.trim()){alert('사상가 / 단원과 원문 선지를 입력해 주세요.');return;}if(recordType==='correction')for(const row of pairContainer.children){const wrong=row.querySelector('.wrong-input').value,target=row.querySelector('.target-select').value,action=row.querySelector('.action-select').value,correct=row.querySelector('.correct-input').value;if(!wrong||!target||(action==='replace'&&!correct.trim())){alert('틀린 부분, 교정 위치, 올바른 부분을 확인해 주세요. × 표시만 선택하면 올바른 부분은 비워도 됩니다.');return;}const correction={wrong,correct:action==='mark'?'':correct,action};if(target!=='all'){const [start,end]=target.split(':').map(Number);if(text.slice(start,end)!==wrong){alert('원문이 바뀌었습니다. 교정 위치를 다시 선택해 주세요.');return;}correction.start=start;correction.end=end;}else correction.occurrence='all';corrections.push(correction);}const spans=corrections.flatMap(c=>Number.isInteger(c.start)?[{start:c.start,end:c.end}]:occurrences(text,c.wrong)).sort((a,b)=>a.start-b.start);if(spans.some((m,i)=>i>0&&m.start<spans[i-1].end)){alert('교정할 부분끼리 겹칩니다. 같은 위치를 중복 지정하지 않도록 수정해 주세요.');return;}const thinker=document.getElementById('thinker').value.trim(),reasonTag=document.getElementById('reasonTag').value,source=document.getElementById('sourceInput').value.trim(),memo=document.getElementById('memo').value.trim();if(editingId!==null){const index=notes.findIndex(n=>String(n.id)===String(editingId));if(index<0){alert('수정할 선지를 찾지 못했습니다.');return;}const old=notes[index],updated={...old,thinker,reasonTag,source,memo,originalText:text,corrections,recordType};if(getCategory(old)===getCategory(updated))notes[index]=updated;else{notes.splice(index,1);notes.push(updated);}}else notes.push({id:nextId(),thinker,reasonTag,source,memo,originalText:text,corrections,recordType,isStar:false});saveNotes();updateFilterOptions();renderNotes();cancelEdit();});
originalInput.addEventListener('input',()=>{for(const row of pairContainer.children)updateTargetOptions(row,'');});
function updateFilterOptions(){syncCategoryOrder();const selected=filterThinker.value;filterThinker.replaceChildren();const all=document.createElement('option');all.value='ALL';all.textContent='전체 사상가';filterThinker.appendChild(all);categoryOrder.forEach(c=>{const o=document.createElement('option');o.value=c;o.textContent=c;filterThinker.appendChild(o);});if(categoryOrder.includes(selected))filterThinker.value=selected;}
function toggleStar(id){notes=notes.map(n=>String(n.id)===String(id)?{...n,isStar:!n.isStar}:n);saveNotes();renderNotes();}
function setViewMode(mode,button){currentViewMode=mode;document.querySelectorAll('.seg-btn').forEach(b=>b.classList.remove('active'));button.classList.add('active');renderNotes();}
function buildSentenceHTML(text,corrections,mode){let html='',pos=0;collectMatches(text,corrections).forEach(m=>{html+=`<span class="text-chunk">${escapeHtml(text.slice(pos,m.start))}</span>`;if(mode==='correct-only')html+=m.mark?'<span class="correct-badge mark-badge">×</span>':`<span class="correct-badge" style="display:inline-block;margin:0 2px;">${escapeHtml(m.correct)}</span>`;else html+=`<span class="correction-container"><span class="wrong-badge">${escapeHtml(m.wrong)}</span><span class="correction-below">${m.mark?'<span class="correct-badge mark-badge">×</span>':`<span class="down-arrow">↓</span><span class="correct-badge">${escapeHtml(m.correct)}</span>`}</span></span>`;pos=m.end;});return html+`<span class="text-chunk">${escapeHtml(text.slice(pos))}</span>`;}
function moveCategoryTo(category,target){syncCategoryOrder();const from=categoryOrder.indexOf(category);if(from<0||!Number.isInteger(target)||target<0||target>=categoryOrder.length)return;categoryOrder.splice(from,1);categoryOrder.splice(target,0,category);saveNotes();updateFilterOptions();renderNotes();}
function moveNoteTo(id,target){const note=notes.find(n=>String(n.id)===String(id));if(!note)return;const category=getCategory(note),group=notes.filter(n=>getCategory(n)===category),from=group.indexOf(note);if(!Number.isInteger(target)||target<0||target>=group.length)return;group.splice(from,1);group.splice(target,0,note);let i=0;notes=notes.map(n=>getCategory(n)===category?group[i++]:n);saveNotes();renderNotes();}
function askPosition(label,current,total){const s=prompt(`${label}\n이동할 위치 (1~${total})`,String(current+1));if(s===null||!s.trim())return null;const n=Number(s);if(!Number.isInteger(n)||n<1||n>total){alert('유효한 위치 번호를 입력해 주세요.');return null;}return n-1;}
function deleteNote(id){if(confirm('선지를 삭제할까요?')){if(String(editingId)===String(id))cancelEdit();notes=notes.filter(n=>String(n.id)!==String(id));saveNotes();updateFilterOptions();renderNotes();}}
function handleNoteAction(event){const b=event.target.closest('button[data-action]');if(!b||!noteList.contains(b)||b.disabled)return;const a=b.dataset.action;if(a.startsWith('group-')){const i=Number(b.dataset.groupIndex),c=categoryOrder[i];if(a==='group-up')moveCategoryTo(c,i-1);if(a==='group-down')moveCategoryTo(c,i+1);if(a==='group-jump'){const n=askPosition('단원 순서',i,categoryOrder.length);if(n!==null)moveCategoryTo(c,n);}}else{const note=notes[Number(b.dataset.noteIndex)];if(!note)return;if(a==='edit'){startEdit(note);return;}if(a==='star'){toggleStar(note.id);return;}if(a==='delete'){deleteNote(note.id);return;}const i=getNoteNumber(note)-1,total=notes.filter(n=>getCategory(n)===getCategory(note)).length;if(a==='note-up')moveNoteTo(note.id,i-1);if(a==='note-down')moveNoteTo(note.id,i+1);if(a==='note-jump'){const n=askPosition('선지 순서',i,total);if(n!==null)moveNoteTo(note.id,n);}}}
function renderNotes(){syncCategoryOrder();noteList.innerHTML='';const selected=filterThinker.value,star=filterStar.value==='STAR',filtered=notes.filter(n=>(selected==='ALL'||getCategory(n)===selected)&&(!star||n.isStar)),all=selected==='ALL'&&!star;if(!filtered.length){noteList.innerHTML='<div style="text-align:center;color:#94a3b8;padding:50px;">등록된 오답 선지가 없습니다.</div>';return;}categoryOrder.forEach((c,gi)=>{const group=filtered.filter(n=>getCategory(n)===c);if(!group.length)return;const full=notes.filter(n=>getCategory(n)===c),card=document.createElement('div');card.className=`thinker-group-card ${currentViewMode==='blind'?'blind-active':''}`;const gb=(a,label,disabled)=>`<button type="button" class="order-btn" data-action="${a}" data-group-index="${gi}" ${disabled?'disabled':''}>${label}</button>`;let items='';group.forEach(note=>{const i=notes.indexOf(note),number=getNoteNumber(note),nb=(a,label,disabled=false)=>`<button type="button" class="order-btn" data-action="${a}" data-note-index="${i}" ${disabled?'disabled':''}>${label}</button>`,sentence=buildSentenceHTML(note.originalText,note.corrections,currentViewMode),line=currentViewMode==='correct-only'?`<div class="full-correct-line"><b>${number}.</b> ${sentence}</div>`:`<div class="sentence-row"><span style="color:#dc2626;font-weight:800;margin-right:6px;">[기출 ${number}]</span> ${sentence}</div>`;items+=`<div class="item-row-container"><div class="note-control-bar"><div class="item-meta"><button type="button" class="star-btn ${note.isStar?'active':''}" data-action="star" data-note-index="${i}">★</button>${isConfusedNote(note)?'<span class="reason-tag confused-tag">헷갈려서 기록 · 교정 없음</span>':''}${note.reasonTag?`<span class="reason-tag">${escapeHtml(note.reasonTag)}</span>`:''}${note.source?`<span style="font-size:.75rem;color:#64748b;">(${escapeHtml(note.source)})</span>`:''}</div><div class="order-controls">${nb('note-up','▲',star||number===1)}${nb('note-down','▼',star||number===full.length)}${nb('note-jump','위치…',star||full.length<2)}${nb('edit','수정')}${nb('delete','삭제')}</div></div>${line}${note.memo?`<div class="memo-card">💡 <b>포인트:</b> ${escapeHtml(note.memo)}</div>`:''}</div>`;});card.innerHTML=`<div class="thinker-group-header"><span>📌 ${escapeHtml(c)}</span><div class="group-header-tools"><span class="count-tag">${group.length}개 항목</span><div class="order-controls">${gb('group-up','▲',!all||gi===0)}${gb('group-down','▼',!all||gi===categoryOrder.length-1)}${gb('group-jump','위치…',!all||categoryOrder.length<2)}</div></div></div><div class="item-list">${items}</div>`;noteList.appendChild(card);});scheduleCorrectionLayout();}
function scheduleCorrectionLayout(){if(layoutFrame)cancelAnimationFrame(layoutFrame);layoutFrame=requestAnimationFrame(()=>{layoutFrame=0;layoutWebCorrections();});}
function layoutWebCorrections(){noteList.querySelectorAll('.sentence-row').forEach(row=>{row.style.lineHeight='';row.style.marginBottom='';const containers=[...row.querySelectorAll('.correction-container')];if(!containers.length)return;const width=Math.max(40,row.getBoundingClientRect().width-8);containers.forEach(c=>{const badge=c.querySelector('.correct-badge');badge.style.maxWidth=width+'px';badge.style.transform='';});const height=Math.max(...containers.map(c=>c.querySelector('.correction-below').getBoundingClientRect().height)),style=getComputedStyle(row),base=parseFloat(style.lineHeight)||parseFloat(style.fontSize)*2.3;if(row.getBoundingClientRect().height>base*1.45)row.style.lineHeight=Math.max(base,parseFloat(style.fontSize)*1.6+height+8)+'px';const bounds=row.getBoundingClientRect();let lowest=bounds.bottom;containers.forEach(c=>{const badge=c.querySelector('.correct-badge'),r=badge.getBoundingClientRect();let shift=0;if(r.left<bounds.left+4)shift=bounds.left+4-r.left;else if(r.right>bounds.right-4)shift=bounds.right-4-r.right;if(shift)badge.style.transform=`translateX(${shift}px)`;lowest=Math.max(lowest,c.querySelector('.correction-below').getBoundingClientRect().bottom);});row.style.marginBottom=Math.ceil(Math.max(12,lowest-bounds.bottom+10))+'px';});}
function exportJSON(){syncCategoryOrder();const blob=new Blob([JSON.stringify({version:13,notes,categoryOrder},null,2)],{type:'application/json;charset=utf-8'});downloadBlob(blob,`생윤_오답노트_백업_${new Date().toISOString().slice(0,10)}.json`);}
function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
function importJSON(){document.getElementById('fileInput').click();}
function parseBackup(data){const legacy=Array.isArray(data),list=legacy?data:data?.notes;if(!Array.isArray(list)||!list.every(n=>n&&typeof n.originalText==='string'))throw new Error('올바른 노트 백업이 아닙니다.');const used=new Set();let next=Date.now();const normalized=list.map(n=>{let id=Number(n.id);if(!Number.isFinite(id)||used.has(id)){while(used.has(next))next++;id=next++;}used.add(id);return {...n,id,thinker:String(n.thinker||''),memo:String(n.memo||''),reasonTag:String(n.reasonTag||''),source:String(n.source||''),corrections:(Array.isArray(n.corrections)?n.corrections:[]).map(c=>({...c,wrong:String(c.wrong||''),correct:String(c.correct||'')}))};});if(legacy)normalized.sort((a,b)=>a.id-b.id);return {notes:normalized,categoryOrder:legacy?[]:(Array.isArray(data.categoryOrder)?data.categoryOrder.filter(c=>typeof c==='string'):[])};}
function loadJSON(event){const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=e=>{try{const p=parseBackup(JSON.parse(e.target.result));notes=p.notes;categoryOrder=p.categoryOrder;cancelEdit();saveNotes();updateFilterOptions();renderNotes();alert('노트와 정렬 순서를 불러왔습니다.');}catch(error){alert('불러오기 실패: '+error.message);}finally{event.target.value='';}};reader.readAsText(file);}
filterThinker.addEventListener('change',renderNotes);noteList.addEventListener('click',handleNoteAction);window.addEventListener('resize',scheduleCorrectionLayout);
document.addEventListener('DOMContentLoaded',()=>{cancelEdit();saveNotes();updateFilterOptions();renderNotes();if(document.fonts)document.fonts.ready.then(scheduleCorrectionLayout);if(window.ResizeObserver){let last=-1;new ResizeObserver(e=>{const width=Math.round(e[0].contentRect.width);if(width!==last){last=width;scheduleCorrectionLayout();}}).observe(noteList);}});
// Flove V2 screen adapter
FloveSync.register({editing:()=>editingId!==null,refresh:()=>{notes=FloveSync.readArray(NOTES_KEY);const raw=localStorage.getItem(LAYOUT_KEY);storedLayout=raw===null?{}:JSON.parse(raw);categoryOrder=Array.isArray(storedLayout.categoryOrder)?storedLayout.categoryOrder:[];updateFilterOptions();renderNotes();}});

